#!/bin/bash

set -eo pipefail

HERE=`dirname $0`

ready() {
    echo " -----> Starting liveness script."

    # Check web server.

    echo " -----> Checking server is working."

    python $HERE/check-server.py

    # Check database.

    echo " -----> Checking database is working."

    if [ x"$DATABASE_URL" != x"" -o x"$DATABASE_HOST" != x"" ]; then
        (cat - | python manage.py shell --plain) << !
import runpy
_ = runpy.run_path('$HERE/check-database.py')
!
    fi

    echo " -----> Stopping liveness script."
}

function alarm
{
   (
     sleep $1
     ps -p $$ > /dev/null
     if [ $? -eq 0 ] ; then
       kill -TERM $$
     fi
   ) &
}

# Abort after 2 seconds as timeouts on probe scripts do
# not work due to lack of timeouts on running docker exec.

alarm 2

ready 2>&1 | tee -a /proc/1/fd/1
