#!/bin/bash

# This is a 'build' action hook script. This script must be executable
# and will be run by the S2I process after the original S2I 'assemble'
# script has been run. This hook is to allow a user to run additional
# build steps which may need the source code or build artefacts in
# place, or to setup any data required for the application.

set -eo pipefail

# Dump out the set of environment variables which were used by the build.

echo " -----> Environment variables set for build script."

env

# Dump out the name of the current working directory.

echo " -----> Current working directory."

pwd

# Run the application specific build steps for this project.

echo " -----> Running collection of Django static resources."

python manage.py collectstatic --noinput

echo " -----> Creating directory for uploaded image files."

mkdir -p media/images && chmod g+w media/images

# Remove the wheelhouse if it exists.

echo " -----> Removing wheelhouse directory from final image."

rm -rf /opt/app-root/src/.s2i/wheelhouse

# Dump out the contents of the current working directory.

echo " -----> Contents of the current working directory after build run."

ls -lasR .
